module.exports = {
    "req": {
        "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
    },
    "info": {
        "nameAccount": "2852199100",
        "kfuin": "2852199100",
        "name": "Guest",
        "face": "",
        "mobile": "",
        "loginUin": "2852199100",
        "loginFace": "",
        "loginName": "",
        "isAdmin": 1
    },
    "nav": {
        "headers": [{
            "name": "社媒管理",
            "url": "https://oaadmin.qidian.qq.com/mp/imgTxtMaterial",
            "openNew": 0,
            "isSelected": 0
        }, {
            "name": "推广分析",
            "url": "https://oaadmin.qidian.qq.com/ea/daTrack/index",
            "openNew": 0,
            "isSelected": 1
        }, {
            "name": "销售接待",
            "url": "https://oaadmin.qidian.qq.com/tp/wpa",
            "openNew": 0,
            "isSelected": 0
        }, {
            "name": "通讯录",
            "url": "https://oaadmin.qidian.qq.com/cc/callContacts",
            "openNew": 0,
            "isSelected": 0
        }, {
            "name": "客户库",
            "url": "https://oaadmin.qidian.qq.com/cl/CustomerClone",
            "openNew": 0,
            "isSelected": 0
        }, {
            "name": "管理",
            "url": "https://oaadmin.qidian.qq.com/mng/org",
            "openNew": 0,
            "isSelected": 0
        }]
    },
    "menu": [{
        "name": "流量分析",
        "subMenu": [{
            "id": 105,
            "nav": "推广分析",
            "name": "广告跟踪",
            "url": "https://oaadmin.qidian.qq.com/ea/daTrack/index",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-adTrack",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 109,
            "nav": "推广分析",
            "name": "关键词",
            "url": "https://oaadmin.qidian.qq.com/ea/semTrack/index",
            "isSelected": 1,
            "isExpanded": 1,
            "className": "icon-nav-searchTrack",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 110,
            "nav": "推广分析",
            "name": "流量效果评估",
            "url": "https://oaadmin.qidian.qq.com/ea/flowEval/evalIndex",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-flowAnalyse",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "线下分析",
        "subMenu": [{
            "id": 111,
            "nav": "推广分析",
            "name": "二维码推广管理",
            "url": "https://oaadmin.qidian.qq.com/ea/qrcode/list",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-qrCode",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 124,
            "nav": "推广分析",
            "name": "网址二维码分析",
            "url": "https://oaadmin.qidian.qq.com/ea/qrcode/track",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-webQrCodeAna",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 123,
            "nav": "推广分析",
            "name": "公众号二维码分析",
            "url": "https://oaadmin.qidian.qq.com/ea/publicQrcode/track",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-mpQrCodeAna",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 25,
            "nav": "推广分析",
            "name": "商圈人群",
            "url": "https://oaadmin.qidian.qq.com/ea/heatMap/show",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-circleHot",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "微信分析",
        "subMenu": [{
            "id": 117,
            "nav": "推广分析",
            "name": "微信推广管理",
            "url": "https://oaadmin.qidian.qq.com/ea/social/index",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-wxPromotionMng",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 118,
            "nav": "推广分析",
            "name": "微信推广分析",
            "url": "https://oaadmin.qidian.qq.com/ea/social/analysis",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-wxPromotionAna",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 119,
            "nav": "推广分析",
            "name": "传播分析",
            "url": "https://oaadmin.qidian.qq.com/ea/social/spread",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-propagationAna",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 120,
            "nav": "推广分析",
            "name": "关键用户",
            "url": "https://oaadmin.qidian.qq.com/ea/social/key",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-keyUser",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "转化分析",
        "subMenu": [{
            "id": 114,
            "nav": "推广分析",
            "name": "转化目标管理",
            "url": "https://oaadmin.qidian.qq.com/ea/cta/list",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-transObjectMng",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 113,
            "nav": "推广分析",
            "name": "转化目标分析",
            "url": "https://oaadmin.qidian.qq.com/ea/cta/track",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-transObjectAnalysis",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 116,
            "nav": "推广分析",
            "name": "归因模型",
            "url": "https://oaadmin.qidian.qq.com/ea/wts/attribution/defaultParam",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-attributionModel",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 104,
            "nav": "推广分析",
            "name": "转化漏斗",
            "url": "https://oaadmin.qidian.qq.com/ea/wts/pathConversion/init",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-transFunnel",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 107,
            "nav": "推广分析",
            "name": "指标管理",
            "url": "https://oaadmin.qidian.qq.com/ea/wts/targetManagement/init",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-targetMng",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "行为分析",
        "subMenu": [{
            "id": 115,
            "nav": "推广分析",
            "name": "事件分析",
            "url": "https://oaadmin.qidian.qq.com/ea/cta/event",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-eventAnalysis",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 47,
            "nav": "推广分析",
            "name": "访客路径",
            "url": "https://oaadmin.qidian.qq.com/ea/pathStat/pathFlow",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-visitorPath",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 106,
            "nav": "推广分析",
            "name": "访客细查",
            "url": "https://oaadmin.qidian.qq.com/ea/visitorEval/list",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-visitorDetail",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "实时分析",
        "subMenu": [{
            "id": 121,
            "nav": "推广分析",
            "name": "实时流量",
            "url": "https://oaadmin.qidian.qq.com/ea/wts/realtime/ov",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-realtimeTraffic",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "网站分析",
        "subMenu": [{
            "id": 55,
            "nav": "推广分析",
            "name": "应用趋势",
            "url": "https://oaadmin.qidian.qq.com/ea/mtafor/appTrend",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-appTrend",
            "openNew": 1,
            "isNew": 0
        }, {
            "id": 56,
            "nav": "推广分析",
            "name": "访客分析",
            "url": "https://oaadmin.qidian.qq.com/ea/mtafor/userAnalysis",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-visitorAnalyse",
            "openNew": 1,
            "isNew": 0
        }, {
            "id": 57,
            "nav": "推广分析",
            "name": "客户端分析",
            "url": "https://oaadmin.qidian.qq.com/ea/mtafor/clientAnalysis",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-clientAnalyse",
            "openNew": 1,
            "isNew": 0
        }, {
            "id": 58,
            "nav": "推广分析",
            "name": "页面分析",
            "url": "https://oaadmin.qidian.qq.com/ea/mtafor/pageAnalysis",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-pageAnalyse",
            "openNew": 1,
            "isNew": 0
        }, {
            "id": 59,
            "nav": "推广分析",
            "name": "来源分析",
            "url": "https://oaadmin.qidian.qq.com/ea/mtafor/originAnalysis",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-sourceAnalyse",
            "openNew": 1,
            "isNew": 0
        }]
    }, {
        "name": "受众人群",
        "subMenu": [{
            "id": 27,
            "nav": "推广分析",
            "name": "人群管理",
            "url": "https://oaadmin.qidian.qq.com/ea/packages/index",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-groupMng",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 28,
            "nav": "推广分析",
            "name": "号码包人群",
            "url": "https://oaadmin.qidian.qq.com/ea/packages/createView",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-phonePack",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 26,
            "nav": "推广分析",
            "name": "相似人群",
            "url": "https://oaadmin.qidian.qq.com/ea/packages/createLooklikeView",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-similarGroup",
            "openNew": 0,
            "isNew": 0
        }, {
            "id": 52,
            "nav": "推广分析",
            "name": "自定义人群",
            "url": "https://oaadmin.qidian.qq.com/ea/packages/custom",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-customGroup",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "市场聆听",
        "subMenu": [{
            "id": 48,
            "nav": "推广分析",
            "name": "舆情监测",
            "url": "https://oaadmin.qidian.qq.com/ea/marketMonitor/list",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-keyword",
            "openNew": 0,
            "isNew": 0
        }]
    }, {
        "name": "代码部署",
        "subMenu": [{
            "id": 31,
            "nav": "推广分析",
            "name": "代码安装",
            "url": "https://oaadmin.qidian.qq.com/ea/wts/mta/index",
            "isSelected": 0,
            "isExpanded": 1,
            "className": "icon-nav-codeDeploy",
            "openNew": 0,
            "isNew": 0
        }]
    }],
    "data": {
        "index": 1,
        "count": 15,
        "total": 27,
        "records": [{
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 128,
            "createTime": "2017-03-17 13:09",
            "status": 2
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 120,
            "createTime": "2017-02-16 19:13",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 119,
            "createTime": "2017-02-16 16:20",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 118,
            "createTime": "2017-02-14 14:19",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 117,
            "createTime": "2017-02-14 14:15",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 116,
            "createTime": "2017-02-14 14:14",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 115,
            "createTime": "2017-02-14 10:52",
            "status": 1
        }, {
            "file": "2013CSV",
            "source": "百度",
            "id": 107,
            "createTime": "2016-09-26 17:58",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 105,
            "createTime": "2016-09-26 17:27",
            "status": 1
        }, {
            "file": "senselock_关键词_2016-09-21",
            "source": "百度",
            "id": 101,
            "createTime": "2016-09-26 11:38",
            "status": 1
        }, {
            "file": "senselock_关键词_2016-09-21",
            "source": "百度",
            "id": 100,
            "createTime": "2016-09-26 10:35",
            "status": 1
        }, {
            "file": "字段缺失-其他字段",
            "source": "百度",
            "id": 97,
            "createTime": "2016-09-13 12:02",
            "status": 1
        }, {
            "file": "CSV-2016afdsafadsfgsdgfsdfgdsfgsdgffdsgfdssdfasfdasdfasfdsadfasdfasdfasdfsadfsadZxcsdfasadff真舒服噶vdzsfgsadfg",
            "source": "百度",
            "id": 95,
            "createTime": "2016-09-13 12:00",
            "status": 1
        }, {
            "file": "CSV-2016 - 副本khsgdjhgashfdghsagjhfdgajhsgfdjhgajhsgdfjhgdajhsagfdgawsfqw",
            "source": "百度",
            "id": 94,
            "createTime": "2016-09-13 12:00",
            "status": 1
        }, {
            "file": "CSV-2016",
            "source": "百度",
            "id": 93,
            "createTime": "2016-09-13 10:52",
            "status": 1
        }],
        "hasFWSet": true,
        "hadUploaded": 2
    },
    "branch": "trunk"
}
